import { Song, SearchResult } from '@/types';
import { searchYouTube } from './youtube';
import { normalizeCoverUrl } from './utils';

const SOUNDCLOUD_CLIENT_ID = process.env.NEXT_PUBLIC_SOUNDCLOUD_CLIENT_ID || '';

// Search SoundCloud for tracks
export async function searchSoundCloud(query: string, limit = 20): Promise<SearchResult> {
  try {
    const response = await fetch(
      `https://api-v2.soundcloud.com/search/tracks?q=${encodeURIComponent(query)}&limit=${limit}&client_id=${SOUNDCLOUD_CLIENT_ID}`
    );
    const data = await response.json();
    if (!data.collection) return { songs: [] };
    const songs = data.collection
      .filter((item: any) => item.streamable)
      .map((item: any) => ({
        id: `sc-${item.id}`,
        title: item.title,
        artist: item.user?.username || 'Unknown',
        coverUrl: normalizeCoverUrl(item.artwork_url?.replace('large', 't500x500')) || `https://picsum.photos/seed/${item.id}/300/300`,
        duration: Math.floor(item.duration / 1000),
        source: 'soundcloud' as const,
        sourceId: item.id.toString(),
      }));
    return { songs };
  } catch (error) {
    console.error('SoundCloud search failed:', error);
    return { songs: [] };
  }
}

// Search both YouTube and SoundCloud
export async function searchAll(query: string): Promise<Song[]> {
  const [ytResults, scResults] = await Promise.all([
    searchYouTube(query),
    searchSoundCloud(query),
  ]);
  const allSongs = [...ytResults.songs, ...scResults.songs];
  return allSongs.sort(() => Math.random() - 0.5);
}

// Generate a unique image URL per song using picsum.photos with a deterministic seed
// Using both title and artist ensures every song gets a unique image
function getAlbumCover(title: string, artist = ''): string {
  const base = title.toLowerCase().replace(/[^a-z0-9]/g, '');
  const artistPart = artist.toLowerCase().replace(/[^a-z0-9]/g, '');
  const seed = `${base}-${artistPart || base}`;
  // Create a hash-based variant for more image diversity
  let hash = 5381;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) + hash) + seed.charCodeAt(i);
  }
  const variant = Math.abs(hash) % 999;
  return `https://picsum.photos/seed/${seed}-${variant}/400/400`;
}

// Mock search — uses picsum.photos for consistent images, YouTube IDs for audio
export async function searchMock(query: string): Promise<Song[]> {
  const mockSongs: Song[] = [
    {
      id: 'mock-1',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      coverUrl: getAlbumCover('Blinding Lights', 'The Weeknd'),
      duration: 200,
      source: 'youtube',
      sourceId: 'fJ9rZzT0Z2g',
      streamUrl: 'https://www.youtube.com/watch?v=fJ9rZzT0Z2g',
    },
    {
      id: 'mock-2',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      coverUrl: getAlbumCover('Shape of You', 'Ed Sheeran'),
      duration: 234,
      source: 'youtube',
      sourceId: 'JGwWNGJdvx8',
      streamUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    },
    {
      id: 'mock-3',
      title: 'Bohemian Rhapsody',
      artist: 'Queen',
      coverUrl: getAlbumCover('Bohemian Rhapsody', 'Queen'),
      duration: 355,
      source: 'youtube',
      sourceId: 'fJ9rZzT0Z2g',
      streamUrl: 'https://www.youtube.com/watch?v=fJ9rZzT0Z2g',
    },
    {
      id: 'mock-4',
      title: 'Hotel California',
      artist: 'Eagles',
      coverUrl: getAlbumCover('Hotel California', 'Eagles'),
      duration: 391,
      source: 'youtube',
      sourceId: 'BciS5krYL80',
      streamUrl: 'https://www.youtube.com/watch?v=BciS5krYL80',
    },
    {
      id: 'mock-5',
      title: 'Stairway to Heaven',
      artist: 'Led Zeppelin',
      coverUrl: getAlbumCover('Stairway to Heaven', 'Led Zeppelin'),
      duration: 482,
      source: 'youtube',
      sourceId: 'QkF3oxPcKi8',
      streamUrl: 'https://www.youtube.com/watch?v=QkF3oxPcKi8',
    },
    {
      id: 'mock-6',
      title: 'Imagine',
      artist: 'John Lennon',
      coverUrl: getAlbumCover('Imagine', 'John Lennon'),
      duration: 187,
      source: 'youtube',
      sourceId: 'YkgkThdzX-8',
      streamUrl: 'https://www.youtube.com/watch?v=YkgkThdzX-8',
    },
    {
      id: 'mock-7',
      title: 'Smells Like Teen Spirit',
      artist: 'Nirvana',
      coverUrl: getAlbumCover('Smells Like Teen Spirit', 'Nirvana'),
      duration: 301,
      source: 'youtube',
      sourceId: 'hTWKbfoikeg',
      streamUrl: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
    },
    {
      id: 'mock-8',
      title: 'Billie Jean',
      artist: 'Michael Jackson',
      coverUrl: getAlbumCover('Billie Jean', 'Michael Jackson'),
      duration: 294,
      source: 'youtube',
      sourceId: 'Zi_XLOBDo_Y',
      streamUrl: 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y',
    },
    {
      id: 'mock-9',
      title: 'Believer',
      artist: 'Imagine Dragons',
      coverUrl: getAlbumCover('Believer', 'Imagine Dragons'),
      duration: 204,
      source: 'youtube',
      sourceId: '7wtfhZwyrcc',
      streamUrl: 'https://www.youtube.com/watch?v=7wtfhZwyrcc',
    },
    {
      id: 'mock-10',
      title: 'Let It Be',
      artist: 'The Beatles',
      coverUrl: getAlbumCover('Let It Be', 'The Beatles'),
      duration: 243,
      source: 'youtube',
      sourceId: 'QDYfEBYipNM',
      streamUrl: 'https://www.youtube.com/watch?v=QDYfEBYipNM',
    },
    {
      id: 'mock-11',
      title: 'Africa',
      artist: 'Toto',
      coverUrl: getAlbumCover('Africa', 'Toto'),
      duration: 295,
      source: 'youtube',
      sourceId: 'FTQbiNvZqaY',
      streamUrl: 'https://www.youtube.com/watch?v=FTQbiNvZqaY',
    },
    {
      id: 'mock-12',
      title: 'Sweet Child O Mine',
      artist: 'Guns N Roses',
      coverUrl: getAlbumCover('Sweet Child O Mine', 'Guns N Roses'),
      duration: 356,
      source: 'youtube',
      sourceId: '1w7OgIMMRc4',
      streamUrl: 'https://www.youtube.com/watch?v=1w7OgIMMRc4',
    },
    {
      id: 'mock-13',
      title: 'Yesterday',
      artist: 'The Beatles',
      coverUrl: getAlbumCover('Yesterday', 'The Beatles'),
      duration: 125,
      source: 'youtube',
      sourceId: 'wXTJBrWCttc',
      streamUrl: 'https://www.youtube.com/watch?v=wXTJBrWCttc',
    },
    {
      id: 'mock-14',
      title: 'Photograph',
      artist: 'Ed Sheeran',
      coverUrl: getAlbumCover('Photograph', 'Ed Sheeran'),
      duration: 258,
      source: 'youtube',
      sourceId: 'nSDgHBxUbVQ',
      streamUrl: 'https://www.youtube.com/watch?v=nSDgHBxUbVQ',
    },
    {
      id: 'mock-15',
      title: 'Closer',
      artist: 'The Chainsmokers ft. Halsey',
      coverUrl: getAlbumCover('Closer', 'The Chainsmokers ft. Halsey'),
      duration: 245,
      source: 'youtube',
      sourceId: '0zGcUoRlhmw',
      streamUrl: 'https://www.youtube.com/watch?v=0zGcUoRlhmw',
    },
    {
      id: 'mock-16',
      title: 'Shake It Off',
      artist: 'Taylor Swift',
      coverUrl: getAlbumCover('Shake It Off', 'Taylor Swift'),
      duration: 242,
      source: 'youtube',
      sourceId: 'nfWlot6h_JM',
      streamUrl: 'https://www.youtube.com/watch?v=nfWlot6h_JM',
    },
    {
      id: 'mock-17',
      title: 'Dance Monkey',
      artist: 'Tones and I',
      coverUrl: getAlbumCover('Dance Monkey', 'Tones and I'),
      duration: 209,
      source: 'youtube',
      sourceId: 'q0hyYWKXF0Q',
      streamUrl: 'https://www.youtube.com/watch?v=q0hyYWKXF0Q',
    },
    {
      id: 'mock-18',
      title: 'Someone Like You',
      artist: 'Adele',
      coverUrl: getAlbumCover('Someone Like You', 'Adele'),
      duration: 285,
      source: 'youtube',
      sourceId: 'hLQl3WQQoQ0',
      streamUrl: 'https://www.youtube.com/watch?v=hLQl3WQQoQ0',
    },
    {
      id: 'mock-19',
      title: 'Rolling in the Deep',
      artist: 'Adele',
      coverUrl: getAlbumCover('Rolling in the Deep', 'Adele'),
      duration: 228,
      source: 'youtube',
      sourceId: 'rYEDA3JcQqw',
      streamUrl: 'https://www.youtube.com/watch?v=rYEDA3JcQqw',
    },
    {
      id: 'mock-20',
      title: 'Uptown Funk',
      artist: 'Mark Ronson ft. Bruno Mars',
      coverUrl: getAlbumCover('Uptown Funk', 'Mark Ronson'),
      duration: 270,
      source: 'youtube',
      sourceId: 'OPf0YbXqDm0',
      streamUrl: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    },
    {
      id: 'mock-21',
      title: 'Happy',
      artist: 'Pharrell Williams',
      coverUrl: getAlbumCover('Happy', 'Pharrell Williams'),
      duration: 233,
      source: 'youtube',
      sourceId: 'ZbZSe6N_BXs',
      streamUrl: 'https://www.youtube.com/watch?v=ZbZSe6N_BXs',
    },
    {
      id: 'mock-22',
      title: 'Counting Stars',
      artist: 'OneRepublic',
      coverUrl: getAlbumCover('Counting Stars', 'OneRepublic'),
      duration: 257,
      source: 'youtube',
      sourceId: 'hT_nvWreIhg',
      streamUrl: 'https://www.youtube.com/watch?v=hT_nvWreIhg',
    },
    {
      id: 'mock-23',
      title: 'Lean On',
      artist: 'Major Lazer ft. DJ Snake',
      coverUrl: getAlbumCover('Lean On', 'Major Lazer'),
      duration: 176,
      source: 'youtube',
      sourceId: 'YqeW9_5kURI',
      streamUrl: 'https://www.youtube.com/watch?v=YqeW9_5kURI',
    },
    {
      id: 'mock-24',
      title: 'Sunflower',
      artist: 'Post Malone & Swae Lee',
      coverUrl: getAlbumCover('Sunflower', 'Post Malone'),
      duration: 158,
      source: 'youtube',
      sourceId: 'ApXoWvfEYVU',
      streamUrl: 'https://www.youtube.com/watch?v=ApXoWvfEYVU',
    },
    {
      id: 'mock-25',
      title: 'Lose Yourself',
      artist: 'Eminem',
      coverUrl: getAlbumCover('Lose Yourself', 'Eminem'),
      duration: 326,
      source: 'youtube',
      sourceId: '_Yhyp-_hX2s',
      streamUrl: 'https://www.youtube.com/watch?v=_Yhyp-_hX2s',
    },
    {
      id: 'mock-26',
      title: 'Despacito',
      artist: 'Luis Fonsi ft. Daddy Yankee',
      coverUrl: getAlbumCover('Despacito', 'Luis Fonsi'),
      duration: 228,
      source: 'youtube',
      sourceId: 'kJQP7kiw5Fk',
      streamUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    },
    {
      id: 'mock-27',
      title: 'See You Again',
      artist: 'Wiz Khalifa ft. Charlie Puth',
      coverUrl: getAlbumCover('See You Again', 'Wiz Khalifa'),
      duration: 237,
      source: 'youtube',
      sourceId: 'RgKAFK5djSk',
      streamUrl: 'https://www.youtube.com/watch?v=RgKAFK5djSk',
    },
    {
      id: 'mock-28',
      title: 'Perfect',
      artist: 'Ed Sheeran',
      coverUrl: getAlbumCover('Perfect', 'Ed Sheeran'),
      duration: 263,
      source: 'youtube',
      sourceId: '2Vv-BfVoq4g',
      streamUrl: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
    },
    {
      id: 'mock-29',
      title: 'Thunder',
      artist: 'Imagine Dragons',
      coverUrl: getAlbumCover('Thunder', 'Imagine Dragons'),
      duration: 187,
      source: 'youtube',
      sourceId: 'fKopy74weus',
      streamUrl: 'https://www.youtube.com/watch?v=fKopy74weus',
    },
    {
      id: 'mock-30',
      title: 'Havana',
      artist: 'Camila Cabello',
      coverUrl: getAlbumCover('Havana', 'Camila Cabello'),
      duration: 217,
      source: 'youtube',
      sourceId: 'BQ0mxQXmLsk',
      streamUrl: 'https://www.youtube.com/watch?v=BQ0mxQXmLsk',
    },
    // ===== Telugu Film Songs =====
    {
      id: 'tel-1',
      title: 'Naatu Naatu',
      artist: 'Vishal Mishra, Rahul Sipligunj',
      coverUrl: getAlbumCover('Naatu Naatu', 'Vishal Mishra'),
      duration: 275,
      source: 'youtube',
      sourceId: '4_eEgJhsBMo',
      streamUrl: 'https://www.youtube.com/watch?v=4_eEgJhsBMo',
    },
    {
      id: 'tel-2',
      title: 'Samajavaragamana',
      artist: 'Sid Sriram',
      coverUrl: getAlbumCover('Samajavaragamana', 'Sid Sriram'),
      duration: 279,
      source: 'youtube',
      sourceId: 'tflQ33g6I8I',
      streamUrl: 'https://www.youtube.com/watch?v=tflQ33g6I8I',
    },
    {
      id: 'tel-3',
      title: 'Butta Bomma',
      artist: 'Anurag Kulkarni',
      coverUrl: getAlbumCover('Butta Bomma', 'Anurag Kulkarni'),
      duration: 263,
      source: 'youtube',
      sourceId: '2mDCVzruYzQ',
      streamUrl: 'https://www.youtube.com/watch?v=2mDCVzruYzQ',
    },
    {
      id: 'tel-4',
      title: 'Srivalli',
      artist: 'Sid Sriram',
      coverUrl: getAlbumCover('Srivalli', 'Sid Sriram'),
      duration: 294,
      source: 'youtube',
      sourceId: 'txHO7PLGE3o',
      streamUrl: 'https://www.youtube.com/watch?v=txHO7PLGE3o',
    },
    {
      id: 'tel-5',
      title: 'Oo Antava Oo Oo Antava',
      artist: 'Shreya Ghoshal',
      coverUrl: getAlbumCover('Oo Antava', 'Shreya Ghoshal'),
      duration: 286,
      source: 'youtube',
      sourceId: 'u_wB6byrl5k',
      streamUrl: 'https://www.youtube.com/watch?v=u_wB6byrl5k',
    },
    {
      id: 'tel-6',
      title: 'Inkem Inkem Inkem Kaavaale',
      artist: 'Hariharan',
      coverUrl: getAlbumCover('Inkem Inkem', 'Hariharan'),
      duration: 276,
      source: 'youtube',
      sourceId: 'LPeZOE8ZIHI',
      streamUrl: 'https://www.youtube.com/watch?v=LPeZOE8ZIHI',
    },
    {
      id: 'tel-7',
      title: 'Nee Kannu Neeli Samudram',
      artist: 'Jubin Nautiyal',
      coverUrl: getAlbumCover('Nee Kannu Neeli Samudram', 'Jubin Nautiyal'),
      duration: 291,
      source: 'youtube',
      sourceId: 'zZl7vDDN8Ek',
      streamUrl: 'https://www.youtube.com/watch?v=zZl7vDDN8Ek',
    },
    {
      id: 'tel-8',
      title: 'Kalaavathi',
      artist: 'Sid Sriram',
      coverUrl: getAlbumCover('Kalaavathi', 'Sid Sriram'),
      duration: 253,
      source: 'youtube',
      sourceId: 'SfDA33y38GE',
      streamUrl: 'https://www.youtube.com/watch?v=SfDA33y38GE',
    },
    {
      id: 'tel-9',
      title: 'Komuram Bheemudo',
      artist: 'Mangli',
      coverUrl: getAlbumCover('Komuram Bheemudo', 'Mangli'),
      duration: 240,
      source: 'youtube',
      sourceId: 'uBDCl5c-9qM',
      streamUrl: 'https://www.youtube.com/watch?v=uBDCl5c-9qM',
    },
    // ===== Christian Telugu Songs =====
    {
      id: 'ctel-1',
      title: 'Yesu Naamame',
      artist: 'Jeswin Smith',
      coverUrl: getAlbumCover('Yesu Naamame', 'Jeswin Smith'),
      duration: 290,
      source: 'youtube',
      sourceId: '_Li5zSks-pw',
      streamUrl: 'https://www.youtube.com/watch?v=_Li5zSks-pw',
    },
    {
      id: 'ctel-2',
      title: 'Neevu Chesina Upakaramulaku',
      artist: 'Sharon',
      coverUrl: getAlbumCover('Neevu Chesina Upakaramulaku', 'Sharon'),
      duration: 310,
      source: 'youtube',
      sourceId: '9oFX7SD5hU0',
      streamUrl: 'https://www.youtube.com/watch?v=9oFX7SD5hU0',
    },
    {
      id: 'ctel-3',
      title: 'Daivam Maitho Undi',
      artist: 'Lotson Felix',
      coverUrl: getAlbumCover('Daivam Maitho Undi', 'Lotson Felix'),
      duration: 345,
      source: 'youtube',
      sourceId: 'IKUp4GtOwf8',
      streamUrl: 'https://www.youtube.com/watch?v=IKUp4GtOwf8',
    },
    {
      id: 'ctel-4',
      title: 'Aradhana',
      artist: 'Jeremiah Thomas',
      coverUrl: getAlbumCover('Aradhana', 'Jeremiah Thomas'),
      duration: 320,
      source: 'youtube',
      sourceId: 'XVqazNBzSF0',
      streamUrl: 'https://www.youtube.com/watch?v=XVqazNBzSF0',
    },
    {
      id: 'ctel-5',
      title: 'Cross Meda Prema',
      artist: 'Solomon Shadrack',
      coverUrl: getAlbumCover('Cross Meda Prema', 'Solomon Shadrack'),
      duration: 280,
      source: 'youtube',
      sourceId: '8cHM1zYJEUw',
      streamUrl: 'https://www.youtube.com/watch?v=8cHM1zYJEUw',
    },
    {
      id: 'ctel-6',
      title: 'Premikosam',
      artist: 'Karthik Vivekanandan',
      coverUrl: getAlbumCover('Premikosam', 'Karthik Vivekanandan'),
      duration: 270,
      source: 'youtube',
      sourceId: 'Imy6yMad2Sc',
      streamUrl: 'https://www.youtube.com/watch?v=Imy6yMad2Sc',
    },
    {
      id: 'ctel-7',
      title: 'Sthorelo Manase',
      artist: 'Ravi Prolaya',
      coverUrl: getAlbumCover('Sthorelo Manase', 'Ravi Prolaya'),
      duration: 295,
      source: 'youtube',
      sourceId: 'VncFXuUooFI',
      streamUrl: 'https://www.youtube.com/watch?v=VncFXuUooFI',
    },
    {
      id: 'ctel-8',
      title: 'Snehithuda',
      artist: 'Ravi Prolaya',
      coverUrl: getAlbumCover('Snehithuda', 'Ravi Prolaya'),
      duration: 310,
      source: 'youtube',
      sourceId: 'zH6Yik46YKw',
      streamUrl: 'https://www.youtube.com/watch?v=zH6Yik46YKw',
    },
    {
      id: 'ctel-9',
      title: 'Devuni Prema',
      artist: 'Salom Morgan',
      coverUrl: getAlbumCover('Devuni Prema', 'Salom Morgan'),
      duration: 335,
      source: 'youtube',
      sourceId: 'VC_mnM8Wf_g',
      streamUrl: 'https://www.youtube.com/watch?v=VC_mnM8Wf_g',
    },
    // ===== Christian English Songs =====
    {
      id: 'ceng-1',
      title: 'Way Maker',
      artist: 'Sinach',
      coverUrl: getAlbumCover('Way Maker', 'Sinach'),
      duration: 258,
      source: 'youtube',
      sourceId: 'QM8jQHE5AAk',
      streamUrl: 'https://www.youtube.com/watch?v=QM8jQHE5AAk',
    },
    {
      id: 'ceng-2',
      title: 'What a Beautiful Name',
      artist: 'Hillsong Worship',
      coverUrl: getAlbumCover('What a Beautiful Name', 'Hillsong Worship'),
      duration: 314,
      source: 'youtube',
      sourceId: 'nQWFzMvCfLE',
      streamUrl: 'https://www.youtube.com/watch?v=nQWFzMvCfLE',
    },
    {
      id: 'ceng-3',
      title: '10,000 Reasons (Bless The Lord)',
      artist: 'Matt Redman',
      coverUrl: getAlbumCover('10000 Reasons', 'Matt Redman'),
      duration: 314,
      source: 'youtube',
      sourceId: 'XtwIT8JjddM',
      streamUrl: 'https://www.youtube.com/watch?v=XtwIT8JjddM',
    },
    {
      id: 'ceng-4',
      title: 'Goodness of God',
      artist: 'Bethel Music',
      coverUrl: getAlbumCover('Goodness of God', 'Bethel Music'),
      duration: 325,
      source: 'youtube',
      sourceId: 'n0FBb6hnwTo',
      streamUrl: 'https://www.youtube.com/watch?v=n0FBb6hnwTo',
    },
    {
      id: 'ceng-5',
      title: 'Amazing Grace (My Chains Are Gone)',
      artist: 'Chris Tomlin',
      coverUrl: getAlbumCover('Amazing Grace', 'Chris Tomlin'),
      duration: 285,
      source: 'youtube',
      sourceId: 'Y-4NFvI5U9w',
      streamUrl: 'https://www.youtube.com/watch?v=Y-4NFvI5U9w',
    },
    {
      id: 'ceng-6',
      title: 'Oceans (Where Feet May Fail)',
      artist: 'Hillsong United',
      coverUrl: getAlbumCover('Oceans', 'Hillsong United'),
      duration: 303,
      source: 'youtube',
      sourceId: 'OP-00EwLdiU',
      streamUrl: 'https://www.youtube.com/watch?v=OP-00EwLdiU',
    },
  ];
  return mockSongs;
}